### ISSUE TITLE
Candidate for removal as not relevant to polaris

### ISSUE THREAD

**Issue by johanrd** [NullVoxPopuli/is-polaris-ready-yet#10]
Not sure how to remove issues specifically (as not relevant for polaris). Here's a candidate: https://github.com/ember-learn/ember-website/issues/1033

(or just close it, of course)

**Comment by NullVoxPopuli** [comment]
I've updated the automation to support excluding things from being scraped.

here is the (automated) PR showing that your link is now removed: https://github.com/NullVoxPopuli/is-polaris-ready-yet/pull/12/files#diff-e37e3a9264ad80f2d0c18ae3e57737ba5ad9c2a752cd3e93add34ed638f23c04L33001


And here is how we remove more things if we want:
https://github.com/NullVoxPopuli/is-polaris-ready-yet/blob/main/github-data/omit.txt
by adding lines to this text file.

I've updated the README as well. thank you!!!
